fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black nbrunner dsnotebooks examples
        pass_filenames: false
        language: system
        files: '(\.py|\.ipynb)$'
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort nbrunner dsnotebooks examples
        pass_filenames: false
        language: system
        files: '\.py$'
  # - repo: local
  #   hooks:
  #     - id: system
  #       name: MyPy
  #       entry: poetry run mypy examples
  #       pass_filenames: false
  #       language: system
  #       files: '\.py$'
  # - repo: local
  #   hooks:
  #     - id: system
  #       name: Pylint
  #       entry: poetry run pylint -j 0 examples
  #       pass_filenames: false
  #       language: system
  #       files: '\.py$'
  -   repo: https://github.com/python-poetry/poetry
      rev: "1.6.1"  # add version here
      hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--check"]
      - id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
